# Production Nginx Config Template with SSL Let's Encrypt support
events {
    worker_connections 2048;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name app.tarunajuara.org;
        return 301 https://$host$request_uri;
    }
}
